createUserTable = "CREATE TABLE USERS( ID VARCHAR(100) PRIMARY KEY, USERNAME VARCHAR(255) UNIQUE, PASSWORD VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PHONENUMBER VARCHAR(255), MOBILEPHONENUMBER VARCHAR(255), ACTIVATED TINYINT(1) DEFAULT 0, CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP, UPDATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP );"
getUserFromUserTable = "SELECT * FROM USERS WHERE ID = '%s'"
insertUserToUserTable = "INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONENUMBER, MOBILEPHONENUMBER) VALUES ('%s','%s','%s','%s','%s','%s','%s')"
